### ISSUE TITLE
Signal service fails due to OS error

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#1]
In GitLab by @pixxie on Dec 13, 2021, 20:08

```
Traceback (most recent call last):
  File "/usr/local/bin/karsa-signal-service", line 33, in <module>
    sys.exit(load_entry_point('karsa-services', 'console_scripts', 'karsa-signal-service')())
  File "/usr/local/bin/karsa-signal-service", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/karsa-backend/src/services/services/SignalProcessorService.py", line 15, in <module>
    from karsatof.lib.TwTool import TwMassCalibrate, TwTof2Mass
  File "/karsa-backend/src/hw_interfaces/karsatof/lib/TwTool.py", line 30, in <module>
    toollib = ct.cdll.LoadLibrary(os.path.join(os.path.dirname(os.path.abspath(__file__)), "dlls", libpath, libname[sys.platform]))
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /karsa-backend/src/hw_interfaces/karsatof/lib/dlls/macos_x86_64/libtwtool.so: cannot open shared object file: No such file or directory
```

**Comment by oskarsari** [comment]
In GitLab by @alexei_upornikov on Dec 14, 2021, 21:56

mentioned in commit 373cc53d15cc4421a3a70c456168b33a0cb54010

**Comment by oskarsari** [comment]
In GitLab by @alexei_upornikov on Dec 27, 2021, 10:28

Missing proprietary Tof library for macos_x86_64: libtwtool.so .

Instead, Tof provides libtwtool.dylib.
@karsa_dev 
TODO:

1. Do we support macos at this stage?
2. If we do, figure out how ctypes is managed under macos.

**Comment by oskarsari** [comment]
In GitLab by @alexei_upornikov on Dec 29, 2021, 10:13

mentioned in commit 3f486d80f8d6bb6fed237340a05873cf0f90637d
