### ISSUE TITLE
Database migration error, v12 -> v13 

### ISSUE THREAD

**Issue by ghost** [ultra-trace-systems/mascope#389]
@philip-chernonog, @oskarsari, I got an error trying to migrate the database from v12 to v13. Migration with `poetry run db-restore`: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\scripts\restore.py", line 206, in run
    restore_table(conn, table_name, table_configs[table_name])
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\scripts\restore.py", line 174, in restore_table
    restore_data_from_backup(cursor, table_name, schema_info["columns"].keys())
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\scripts\restore.py", line 48, in restore_data_from_backup
    cursor.execute(
sqlite3.IntegrityError: UNIQUE constraint failed: sample_file.filename
```

Attempt to start the backend:

```
INFO:     Will watch for changes in these directories: ['C:\\Users\\alvai\\Desktop\\Mascope\\backend']
INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
INFO:     Started reloader process [8484] using StatReload
INFO:     Started server process [25568]
INFO:     Waiting for application startup.
Initializing mascope database
Detected mascope database version: v12
This version of mascope requires: v13
Executing migration pathway
Attempting to migrate mascope database from v12 to v13
Warning: 'db-restore' is an entry point defined in pyproject.toml, but it's not installed as a script. You may get improper `sys.argv[0]`.

The support to run uninstalled scripts will be removed in a future release.

Run `poetry install` to resolve and get rid of this message.

Backup created at C:/mascope_data/database\backup\20240610_133255_restore_backup_mascope.v13.db
⚙️ Schema mismatch detected, restoring workspace.
Schema restoration of workspace completed.
⚙️ Schema mismatch detected, restoring attribute_template.
Schema restoration of attribute_template completed.
⚙️ Schema mismatch detected, restoring instrument_function.
Schema restoration of instrument_function completed.
⚙️ Schema mismatch detected, restoring ionization_mechanism.
Schema restoration of ionization_mechanism completed.
⚙️ Schema mismatch detected, restoring target_compound.
Schema restoration of target_compound completed.
⚙️ Schema mismatch detected, restoring target_collection.
Schema restoration of target_collection completed.
⚙️ Schema mismatch detected, restoring target_ion.
Schema restoration of target_ion completed.
➕ Index idx_target_ion_ionization_mechanism created.
⚙️ Schema mismatch detected, restoring target_isotope.
Schema restoration of target_isotope completed.
⚙️ Schema mismatch detected, restoring target_collection_in_sample_batch.
Schema restoration of target_collection_in_sample_batch completed.
⚙️ Schema mismatch detected, restoring target_compound_in_target_collection.
Schema restoration of target_compound_in_target_collection completed.
⚙️ Schema mismatch detected, restoring match.
Schema restoration of match completed.
➕ Index idx_match_sample_item created.
⚙️ Schema mismatch detected, restoring match_interference.
Schema restoration of match_interference completed.
➕ Index idx_match_interference_sample_item created.
⚙️ Schema mismatch detected, restoring match_rating.
Schema restoration of match_rating completed.
⚙️ Schema mismatch detected, restoring sample_item.
Schema restoration of sample_item completed.
➕ Index idx_sample_item_sample_batch created.
⚙️ Schema mismatch detected, restoring sample_file.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\scripts\restore.py", line 206, in run
    restore_table(conn, table_name, table_configs[table_name])
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\scripts\restore.py", line 174, in restore_table
    restore_data_from_backup(cursor, table_name, schema_info["columns"].keys())
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\scripts\restore.py", line 48, in restore_data_from_backup
    cursor.execute(
sqlite3.IntegrityError: UNIQUE constraint failed: sample_file.filename
Migration from v12 to v13 failed!
Traceback (most recent call last):
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\__init__.py", line 48, in migrate
    migration.run()
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\migration\v13.py", line 16, in run
    subprocess.run(["poetry", "run", "db-restore"], check=True)
  File "C:\Users\alvai\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['poetry', 'run', 'db-restore']' returned non-zero exit status 1.
Command '['poetry', 'run', 'db-restore']' returned non-zero exit status 1.
A copy failed target database is found at C:/mascope_data/database\mascope.debug.db
ERROR:    Traceback (most recent call last):
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\__init__.py", line 48, in migrate
    migration.run()
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\migration\v13.py", line 16, in run
    subprocess.run(["poetry", "run", "db-restore"], check=True)
  File "C:\Users\alvai\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['poetry', 'run', 'db-restore']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\__init__.py", line 112, in init_db
    current_version = migrate(current_version, target_version)
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\__init__.py", line 58, in migrate
    raise RuntimeError("Database migration failed")
RuntimeError: Database migration failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alvai\AppData\Local\pypoetry\Cache\virtualenvs\backend-queOhwGq-py3.10\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\alvai\AppData\Local\pypoetry\Cache\virtualenvs\backend-queOhwGq-py3.10\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\alvai\AppData\Local\pypoetry\Cache\virtualenvs\backend-queOhwGq-py3.10\lib\site-packages\starlette\routing.py", line 654, in startup
    await handler()
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\main.py", line 55, in startup_event
    await init_db()
  File "C:\Users\alvai\Desktop\Mascope\backend\backend\db\__init__.py", line 114, in init_db
    traceback.print_exc(error)
  File "C:\Users\alvai\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\alvai\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 119, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "C:\Users\alvai\AppData\Local\pypoetry\Cache\virtualenvs\backend-queOhwGq-py3.10\lib\site-packages\exceptiongroup\_formatting.py", line 96, in __init__
    self.stack = traceback.StackSummary.extract(
  File "C:\Users\alvai\AppData\Local\Programs\Python\Python310\lib\traceback.py", line 357, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'RuntimeError' and 'int'

ERROR:    Application startup failed. Exiting.
```

**Comment by ghost** [comment]
Updates:
- Migration from mascope.v7.db -> mascope.v13.db was successful.
- Migration from mascope.v12.db taken from  192.168.1.99 -> mascope.v13.db was successful.

I can share the databases if needed.

**Comment by philip-chernonog** [comment]
Cause of this migration failure from v12 to v13 is related to duplicate filenames in the sample_file table, which conflicts with the UNIQUE constraint on the filename column. 

The new [issue](https://github.com/Karsa-Oy/Mascope/issues/394) was created to prevent duplicate filename. 

As an immediate workaround to resolve the migration error and proceed with the v13 update, duplicate entries can be removed directly in the database. This SQL script can be run in DB Browser to delete the duplicates (ExecuteSQL tab, play button, Write Changes)

`
DELETE FROM sample_file
WHERE sample_file_id NOT IN (
    SELECT MIN(sample_file_id)
    FROM sample_file
    GROUP BY filename
);
`

This script can be run in DB Browser Execute SQL tab  to check if there are any filename duplicates in the sample_file records

`
SELECT filename, COUNT(*)
FROM sample_file
GROUP BY filename
HAVING COUNT(*) > 1;
`
